export const DOG_BREEDS = [
  'Labrador Retriever',
  'German Shepherd',
  'Golden Retriever',
  'French Bulldog',
  'Bulldog',
  'Beagle',
  'Poodle',
  'Rottweiler',
  'Yorkshire Terrier',
  'Boxer',
  'Dachshund',
  'Siberian Husky',
  'Shih Tzu',
  'Doberman Pinscher',
  'Australian Shepherd',
  'Great Dane',
  'Cocker Spaniel',
  'Border Collie',
  'Pug',
  'Maltese',
  'Chihuahua',
  'Bichon Frise',
  'Pembroke Welsh Corgi',
  'Boston Terrier',
  'Shetland Sheepdog',
  'Cane Corso',
  'Akita',
  'English Springer Spaniel',
  'Staffordshire Bull Terrier',
  'Belgian Malinois',
  'Newfoundland',
  'Saint Bernard',
  'Alaskan Malamute',
  'Greyhound',
  'Irish Setter',
  'Whippet',
  'Cavalier King Charles Spaniel',
  'Havanese',
  'Weimaraner',
  'Miniature Schnauzer',
  'Dalmatian',
  'Bullmastiff',
  'Shiba Inu',
  'Samoyed',
  'Bernese Mountain Dog',
  'Collie',
  'Basenji',
  'Vizsla',
  'Australian Cattle Dog',
  'Lhasa Apso',
  'Papillon',
  'Scottish Terrier',
  'Airedale Terrier',
  'Rhodesian Ridgeback',
  'Bloodhound',
  'Great Pyrenees',
  'Cairn Terrier',
  'American Staffordshire Terrier',
  'Chinese Shar-Pei',
  'Chow Chow',
  'My breed isn\'t listed'
];